BBBBBBB BBBBBBBBBBB

BBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXXXX XXXXXXXXXXXXX

XXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXX XX
          XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
           XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
           XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
           XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX

        XXXXX
      XXXXX
    XXXXXX
    XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXX XXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX
        XXXX
    XXXXXX
  XXXXXXX
XXXXXXX

XXXX
 FFFF


BBBBBBBB
