BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXXXX X XXXXBBBBBBBB

BBBBB BBBBBBB
    BB BBBB
        XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
        XXXXX XXX XXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXXX
    BBBB
        XXXXXXXXXX X XXXXX XXX XXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXXXXX
            
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXX
    BBBBB
BBBBBBBB
