# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geralId', models.IntegerField()),
                ('dataMovimento', models.DateField()),
                ('unidade', models.CharField(choices=[('3stamina', '3stamina'), ('OUTRA', 'OUTRA')], help_text='Insira a unidade', max_length=20)),
                ('tipo', models.CharField(choices=[('Despesa', 'Despesa'), ('Receita', 'Receita'), ('Saldo', 'Saldo'), ('Reserva', 'Reserva'), ('Transferencia', 'Transferencia')], help_text='Insira o tipo', max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('Alimentação', 'Alimentação'), ('Blackbird Setup', 'Blackbird Setup'), ('Cartão de Crédito', 'Cartão de Crédito'), ('COFINS', 'COFINS'), ('Comercial', 'Comercial'), ('Comissão', 'Comercial'), ('Contabilidade', 'Contabilidade'), ('Convênio Médico', 'Convênio Médico'), ('Convênio Odontológico', 'Convênio Odontológico'), ('CSLL', 'CSLL'), ('DAS', 'DAS'), ('Despesa Administrativa', 'Despesa Administrativa'), ('Despesa Financeira', 'Despesa Financeira'), ('Emprestimos', 'Emprestimos'), ('GPS', 'GPS'), ('Imposto', 'Imposto'), ('Infraestrutura', 'Infraestrutura'), ('INSS', 'INSS'), ('Internet', 'Internet'), ('Investimento', 'Investimento'), ('IOF', 'IOF'), ('IRRF', 'IRRF'), ('ISS', 'ISS'), ('Juros', 'Juros'), ('Motoboy', 'Motoboy'), ('Movimentação', 'Movimentação'), ('Multa', 'Multa'), ('PIS', 'PIS'), ('Prejuizo', 'Prejuizo'), ('Pró Labore', 'Pró Labore'), ('Projetos', 'Projetos'), ('Recisão', 'Recisão'), ('Reserva U3', 'Reserva U3'), ('Salário', 'Salário'), ('Saldo 2016', 'Saldo 2016'), ('Seguro', 'Seguro'), ('Vale Refeição', 'Vale Refeição'), ('Vale Transporte', 'Vale Transporte'), ('Venda Ativo', 'Venda Ativo')], help_text='Insira a categoria', max_length=20)),
                ('origem', models.CharField(blank=True, help_text='Insira a origem', max_length=50)),
                ('destino', models.CharField(blank=True, help_text='Insira o destino', max_length=50)),
                ('observacao', models.CharField(blank=True, help_text='Insira o historico', max_length=200)),
                ('valorReais', models.FloatField()),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], help_text='Insira o status', max_length=20)),
            ],
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accounting',
            unique_together=set([('dataMovimento', 'valorReais', 'observacao', 'status')]),
        ),
    ]
