# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180411_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='nr',
            field=models.CharField(blank=True, help_text='Numero Documento', max_length=20),
        ),
    ]
